import = [
"~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "GeistMono Nerd Font Propo"

[window]
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 4
y = 2
