import = [
"~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
#family = "ZedMono Nerd Font"
#family = "Lilex Nerd Font"
family = "GeistMono Nerd Font"
#family = "RecMonoSmCasual Nerd Font"
#family = "JetBrainsMono Nerd Font"

[window]
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 4
y = 4
