import = [
"C:/Users/dagger/AppData/Roaming/alacritty/theme.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Lilex Nerd Font Propo"

[shell]
program = "wsl ~ tmux"

[window]
decorations = "none"
dynamic_title = false
startup_mode = "Maximized"
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 5
y = 5
