import = [
"~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.5

offset = { y = 3 }
glyph_offset = { y = 1 } #RecMono

#offset = { x = 2 }
#glyph_offset = { x = 1 } #ZedMono

[font.normal]
family = "RecMonoLinear Nerd Font"
#family = "ZedMono Nerd Font"
#family = "Lilex Nerd Font"
#family = "GeistMono Nerd Font"
#family = "JetBrainsMono Nerd Font"

[window]
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 4
y = 4
