import = [
"~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "ZedMono Nerd Font"
#family = "Lilex Nerd Font"

[window]
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 4
y = 2
