import = [
#"C:/Users/dagger/AppData/Roaming/alacritty/theme.toml",
"~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "GeistMono Nerd Font Propo"

#[shell]
#program = "wsl ~ tmux"
#program = "tmux"

[window]
decorations = "none"
dynamic_title = false
startup_mode = "Maximized"
title = "Alacritty"
dynamic_padding = true
option_as_alt = "Both"
opacity = 0.6
blur = true

[window.padding]
x = 5
y = 5
