import = [
"~/.config/alacritty/theme.toml",
"~/.config/alacritty/keybinds.toml"
]

[env]
TERM = "alacritty"

[font]
size = 18
#offset = { y = 4 }
#glyph_offset = { y = 2 } #RecMono

[font.normal]
#family = "RecMonoLinear Nerd Font"
#family = "RecMonoCasual Nerd Font"
#family = "JetBrainsMono Nerd Font"
#family = "GeistMono Nerd Font"
family = "Input Mono"

[window]
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 4
y = 4
