[env]
TERM = "alacritty"

[font]
size = 15
offset = { y = 4 }
glyph_offset = { y = 2 } #RecMono

[font.normal]
#family = "JetBrainsMono Nerd Font"
#family = "RecMonoLinear Nerd Font"
#family = "RecMonoCasual Nerd Font"
family = "RecMonoDuotone Nerd Font Propo"

[window]
dynamic_title = false
decorations = "none"
startup_mode = "SimpleFullscreen"
title = "Touch grass"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 4
y = 0

[general]
import = [
"~/.config/alacritty/theme.toml",
"~/.config/alacritty/keybinds.toml"
]
