import = [
"~/.config/alacritty/theme.toml",
"~/.config/alacritty/keybinds.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18

offset = { y = 4 }
glyph_offset = { y = 2 } #RecMono

[font.normal]
family = "RecMonoLinear Nerd Font"
#family = "RecMonoCasual Nerd Font"
#family = "GeistMono Nerd Font"
#family = "JetBrainsMono Nerd Font"

[window]
title = "Alacritty"
dynamic_padding = true

[window.padding]
x = 4
y = 4
