[colors.primary]
background = '#000000'
foreground = '#B7ACD1'

[colors.cursor]
text = '#130F1A'
cursor = '#B7ACD1'

[colors.normal]
black = '#A88FF5'
red = '#B28DE9'
green = '#BB8BDD'
yellow = '#CE86C5'
blue = '#E181AD'
magenta = '#EA7FA1'
cyan = '#EF7E9B'
white = '#F37C94'

[colors.bright]
black = '#F58FA3'
red = '#F090A6'
green = '#EB90A8'
yellow = '#E191AC'
blue = '#CD93B4'
magenta = '#B995BD'
cyan = '#AF96C1'
white = '#A496C5'
